name: Strip Jupyter widget metadata

on:
  workflow_dispatch:
  push:

permissions:
  contents: write

jobs:
  strip-widgets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Remove metadata.widgets
        run: |
          find . -type f -name '*.ipynb' -print0 |
          while IFS= read -r -d '' nb; do
            jq 'del(.metadata.widgets)' "$nb" > "$nb.tmp" && mv "$nb.tmp" "$nb"
          done
      - name: Commit cleaned notebooks
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "🧹 Strip widget metadata"
